const legacyDiseases = [
  {name:"Community-acquired pneumonia",cat:"Pulmonary",pages:"83–86",tests:["Confirm infiltrate and severity; obtain cultures before antibiotics when severe","Assess aspiration, influenza and MRSA/Pseudomonas risk","Review at 48–72 hours and narrow to results"],options:["Non-severe inpatient: beta-lactam plus macrolide (verify current local CAP guideline)","Alternative: respiratory fluoroquinolone when appropriate","Add MRSA or antipseudomonal coverage only with validated risk factors"],source:"Baseline regimen category only; local resistance and current CAP guidance take priority."},
  {name:"Healthcare-acquired pneumonia",cat:"Pulmonary",pages:"87",tests:["Confirm new infiltrate plus compatible clinical features","Obtain respiratory and blood cultures","Use unit-specific antibiogram and recent antibiotic exposure"],options:["Choose empiric Gram-negative coverage from the local hospital protocol","Add MRSA coverage only when risk or local prevalence supports it","De-escalate promptly when culture and clinical data return"],source:"Historical HCAP terminology is outdated; use current HAP guidance."},
  {name:"Ventilator-associated pneumonia",cat:"Pulmonary",pages:"88–90",tests:["Collect lower respiratory sample before therapy when feasible","Assess shock, prior IV antibiotics and MDR colonisation","Apply local ICU antibiogram"],options:["Empiric antipseudomonal beta-lactam selected by local susceptibility","Consider a second antipseudomonal class only for high resistance risk","Add MRSA coverage according to local risk; de-escalate rapidly"],source:"Requires current ICU protocol; historical guide is baseline context only."},
  {name:"COPD exacerbation",cat:"Pulmonary",pages:"82",tests:["Antibiotics mainly when sputum purulence accompanies increased dyspnoea/volume or ventilation is needed","Exclude pneumonia and heart failure","Check recent antibiotics and prior Pseudomonas"],options:["Select a narrow oral agent per current local guideline when bacterial features are present","Reserve antipseudomonal therapy for defined risk factors","Typical short course if improving, per current protocol"],source:"Avoid antibiotics when bacterial criteria are absent."},
  {name:"Acute bacterial rhinosinusitis",cat:"ENT",pages:"78–79",tests:["Use bacterial criteria: persistent, severe or double-worsening illness","Exclude orbital/intracranial complications","Check immediate beta-lactam allergy"],options:["Amoxicillin/clavulanate is a common first-line category; verify current local dose/duration","Use a guideline-supported allergy alternative based on reaction phenotype","Reassess non-response rather than automatically broadening"],source:"Most acute sinusitis is viral."},
  {name:"Bacterial meningitis",cat:"CNS",pages:"73–74, 77",tests:["Emergency: cultures and immediate empiric therapy must not await delayed imaging/LP","Age, immune status, neurosurgery and resistance change coverage","Dexamethasone timing and public-health actions may apply"],options:["Use current emergency meningitis pathway with age/risk-tailored beta-lactam coverage","Add resistant pneumococcal and Listeria coverage when indicated","Seek urgent ID/neurology input and tailor to CSF/microbiology"],source:"Time-critical; consult current protocol immediately."},
  {name:"Brain abscess",cat:"CNS",pages:"76",tests:["Urgent imaging and neurosurgical assessment","Identify dental/ENT, haematogenous or postoperative source","Obtain abscess culture where feasible"],options:["Empiric therapy must cover likely source flora and anaerobes","Post-neurosurgical disease requires nosocomial Gram-negative/MRSA consideration","Tailor prolonged therapy to drainage, organism and imaging response"],source:"Specialist-managed; source control is central."},
  {name:"Cellulitis",cat:"Skin & soft tissue",pages:"100",tests:["Distinguish non-purulent cellulitis from abscess","Mark margins and assess systemic toxicity","Look for bite, water exposure, diabetic foot or necrotising infection"],options:["Non-purulent: target streptococci with the narrowest suitable beta-lactam","Purulent/MRSA risk: add an agent active against MRSA when indicated","Escalate severe disease and obtain surgical review if deep infection suspected"],source:"Do not use broad Gram-negative coverage for routine uncomplicated cellulitis."},
  {name:"Cutaneous abscess",cat:"Skin & soft tissue",pages:"101",tests:["Incision and drainage is primary therapy","Culture recurrent, severe or complicated abscesses","Assess systemic signs and immune compromise"],options:["Drainage alone may suffice for a small uncomplicated abscess","Add MRSA-active therapy for systemic illness or high-risk features","Use culture to narrow treatment"],source:"Source control comes before broader antibiotics."},
  {name:"Diabetic foot infection",cat:"Skin & soft tissue",pages:"103–104",tests:["Grade severity; assess perfusion and need for urgent surgery","Probe for osteomyelitis and obtain deep tissue specimen","Do not treat an uninfected ulcer"],options:["Mild infection: narrow Gram-positive coverage","Moderate/severe: broaden according to prior cultures, exposure and local flora","Antipseudomonal coverage is not automatic; use specific risk factors"],source:"Multidisciplinary wound, vascular and glycaemic management is required."},
  {name:"Necrotising soft-tissue infection",cat:"Emergency",pages:"107",tests:["Immediate surgical exploration—do not wait for imaging if clinical suspicion is high","Send tissue for Gram stain/culture","Treat shock and organ failure concurrently"],options:["Start broad empiric therapy covering Gram-positive, Gram-negative and anaerobic organisms","Include MRSA-active therapy and a toxin-suppressing agent when indicated","Narrow only after operative and microbiology findings"],source:"Surgical emergency; antibiotics are adjunctive to debridement."},
  {name:"Uncomplicated cystitis",cat:"Urinary",pages:"110–114",tests:["Confirm urinary symptoms; avoid treating asymptomatic bacteriuria except defined exceptions","Review pregnancy, renal function and prior cultures","Check local E. coli susceptibility"],options:["Use a recommended narrow oral urinary agent guided by local resistance","Fosfomycin may be an option for susceptible uncomplicated lower UTI","Avoid agents with poor urinary activity and avoid unnecessary broad therapy"],source:"Do not extrapolate uncomplicated cystitis regimens to pyelonephritis."},
  {name:"Pyelonephritis / urosepsis",cat:"Urinary",pages:"110–114",tests:["Obtain urine culture and blood cultures when systemically ill","Assess obstruction—urgent drainage may be required","Review prior ESBL/MDR organisms and recent antibiotics"],options:["Choose parenteral or oral therapy by severity and local susceptibility","Reserve carbapenem therapy for strong ESBL risk or confirmed susceptibility needs","Narrow promptly and ensure adequate tissue/serum exposure"],source:"Fosfomycin is not appropriate for systemic infection based on this guide."},
  {name:"Biliary tract infection",cat:"Abdominal",pages:"39–40",tests:["Assess obstruction, cholangitis severity and need for urgent drainage","Obtain cultures in severe infection or during drainage","Consider healthcare exposure and prior resistant organisms"],options:["Community-acquired mild/moderate: guideline-supported enteric Gram-negative coverage","Add anaerobic coverage only when anatomy/procedure indicates","Broader therapy for severe or healthcare-associated disease, then narrow"],source:"Source control and biliary drainage are decisive."},
  {name:"Diverticulitis",cat:"Abdominal",pages:"40–41",tests:["Confirm uncomplicated versus abscess/perforation","Selected uncomplicated cases may not need antibiotics under current guidance","Arrange drainage/surgery for complicated disease"],options:["When antibiotics are indicated, cover enteric Gram-negatives and anaerobes","Choose oral versus IV route by severity and absorption","Avoid unnecessarily prolonged courses after adequate source control"],source:"Current practice has changed since 2015; verify modern guidance."},
  {name:"Secondary peritonitis / GI perforation",cat:"Abdominal",pages:"42–46",tests:["Urgent source control assessment","Obtain intra-abdominal cultures in high-risk/severe cases","Differentiate community from healthcare-associated infection"],options:["Use a regimen covering enteric Gram-negatives and anaerobes","Broaden for severe healthcare-associated infection using local antibiogram","Shorten and narrow after effective source control and clinical response"],source:"ID/surgical review recommended for shock, failure or resistant isolates."},
  {name:"C. difficile infection",cat:"Gastrointestinal",pages:"47–50",tests:["Test only clinically significant unexplained diarrhoea","Stop inciting antibiotics and unnecessary acid suppression when possible","Assess fulminant disease: hypotension, ileus or megacolon"],options:["Use current CDI guideline—preferred agents have changed since this baseline","Fulminant CDI requires urgent combination therapy and surgical review","Do not treat an asymptomatic positive test"],source:"Historical regimens are intentionally not shown; consult current CDI guidance."},
  {name:"Catheter-related bloodstream infection",cat:"Bloodstream",pages:"60–64",tests:["Obtain paired peripheral and catheter blood cultures before antibiotics","Assess tunnel infection, prosthetic material and metastatic foci","Determine whether catheter removal is required"],options:["Empiric Gram-positive coverage according to MRSA risk","Add Gram-negative coverage for severe illness or defined risk","Tailor to organism and remove infected device when guideline indicates"],source:"Duration depends on organism, clearance and complications."},
  {name:"Infective endocarditis",cat:"Cardiac",pages:"65–70",tests:["Obtain at least three properly collected blood-culture sets before antibiotics if stable","Perform echo pathway and assess embolic/surgical indications","Identify native versus prosthetic valve/device"],options:["Empiric therapy depends on acuity, valve type and healthcare exposure","Definitive therapy must be organism/MIC-directed","Early ID and cardiac surgery involvement is recommended"],source:"Do not select definitive therapy without microbiology."},
  {name:"Sepsis — no clear source",cat:"Emergency",pages:"99",tests:["Obtain cultures promptly without delaying time-critical therapy","Search for drainable/removable source","Use local syndrome- and unit-specific antibiogram"],options:["Start severity-appropriate empiric therapy covering the most likely source and resistance risks","Avoid reflexively adding every broad agent; individualise to exposure and colonisation","Reassess within hours and de-escalate when source/data emerge"],source:"Emergency management and organ support take priority."}
];

const diseases = [
  {name:"Community-acquired pneumonia - outpatient",cat:"Pulmonary",pages:"39-42",tests:["Confirm CAP and exclude viral bronchitis, pulmonary oedema and tuberculosis","Check comorbidities and antibiotic exposure during the previous 3 months","Assess influenza, MRSA and Pseudomonas risk"],options:["No comorbidity: co-amoxiclav; alternatives cefuroxime or cefpodoxime. ICMR advises beta-lactam over macrolide monotherapy","Comorbidity/recent antibiotic: co-amoxiclav plus azithromycin, clarithromycin or doxycycline; alternative cefuroxime/cefpodoxime plus macrolide/doxycycline","Usual duration: 5 days if clinically stable. Avoid empiric fluoroquinolone in India until TB is excluded"],source:"ICMR 2019 Table 4.2; tailor to current local susceptibility and patient factors."},
  {name:"Community-acquired pneumonia - inpatient",cat:"Pulmonary",pages:"39-42",tests:["Obtain chest imaging and blood cultures in admitted patients","Determine non-ICU versus ICU severity and Pseudomonas risk","Send respiratory sample when severe or MRSA is suspected"],options:["Non-ICU: ceftriaxone plus macrolide/doxycycline; alternative cefotaxime or co-amoxiclav plus macrolide/doxycycline","ICU: ceftriaxone plus macrolide/doxycycline; alternative cefotaxime or piperacillin-tazobactam plus macrolide","ICU with Pseudomonas risk: piperacillin-tazobactam plus macrolide/doxycycline; alternative cefepime or imipenem plus atypical cover. Add vancomycin/teicoplanin only for MRSA risk. Usually 7 days if uncomplicated"],source:"ICMR 2019 Table 4.2; severe disease requires urgent senior/ID review."},
  {name:"Hospital-acquired pneumonia",cat:"Pulmonary / HAI",pages:"116-122",tests:["Confirm pneumonia after at least 48 hours of admission and obtain respiratory culture before therapy","Review prior IV antibiotics, unit antibiogram, shock and MDR colonisation","Distinguish HAP from ventilator-associated pneumonia"],options:["Use one antipseudomonal beta-lactam active on the local ICU antibiogram when MDR risk is low","With shock/high MDR risk, use a locally active antipseudomonal beta-lactam and consider a second different Gram-negative class","Add vancomycin or teicoplanin only for MRSA risk; review culture at 48-72 hours and de-escalate. ICMR duration target for HAP is about 8 days"],source:"ICMR 2019 HAI chapter; exact regimen must follow the current institutional antibiogram."},
  {name:"Ventilator-associated pneumonia",cat:"Pulmonary / HAI",pages:"116-122",tests:["Obtain endotracheal aspirate/BAL before antibiotics when feasible","Assess septic shock, prior antimicrobials and carbapenem-resistant organism risk","Use the ICU-specific antibiogram"],options:["Select empiric antipseudomonal beta-lactam from local susceptibility data","In shock/high resistance risk, combine two active Gram-negative agents from different classes until susceptibility is known","Add MRSA cover only with validated risk; stop redundant agents and target about 7-8 days when response is adequate"],source:"ICMR 2019 VAP guidance; avoid fixed national regimens where local resistance differs."},
  {name:"Acute bacterial rhinosinusitis",cat:"ENT",pages:"35-38",tests:["Treat only persistent symptoms beyond 10 days, double-worsening, or severe fever/facial pain/purulent discharge for 3-4 days","Exclude orbital or intracranial complication","Characterise beta-lactam allergy"],options:["Mild adult disease: amoxicillin","Severe, recent antibiotic or non-response: co-amoxiclav; alternative cefpodoxime","Anaphylactic beta-lactam allergy: doxycycline or a respiratory fluoroquinolone in adults. Duration 5-7 days"],source:"ICMR 2019 section 4.1.6 and Table 4.1; most rhinosinusitis is viral."},
  {name:"Streptococcal pharyngitis",cat:"ENT",pages:"35-38",tests:["Use Centor features and confirm with rapid antigen test/culture when available","Do not test or treat when viral features predominate","Check immediate versus non-anaphylactic penicillin allergy"],options:["Preferred: penicillin V for 10 days","Alternative: amoxicillin for 10 days or single-dose benzathine penicillin","Anaphylactic allergy: clindamycin, clarithromycin or azithromycin; non-anaphylactic allergy: cephalexin or cefadroxil"],source:"ICMR 2019 section 4.1.5 and Table 4.1."},
  {name:"Acute bacterial meningitis",cat:"CNS",pages:"78-81",tests:["Draw two blood-culture sets and obtain CSF urgently when safe; do not delay antibiotics for delayed imaging/LP","Select regimen by age and immune status","Give dexamethasone before or with first antibiotic dose when pneumococcal meningitis is suspected, per protocol"],options:["Age 1 month-50 years: ceftriaxone plus vancomycin; alternative cefotaxime plus vancomycin","Age over 50 years, alcoholism or impaired cell-mediated immunity: ampicillin plus ceftriaxone plus vancomycin; alternative meropenem plus vancomycin","Uncomplicated duration generally 10-14 days, then organism-specific: meningococcus/H. influenzae 7 days; pneumococcus 10-14 days; Listeria 3-6 weeks; Gram-negative meningitis 3 weeks"],source:"ICMR 2019 Table 8.3; this is a medical emergency requiring current local protocol."},
  {name:"Brain abscess",cat:"CNS",pages:"82-83",tests:["Obtain blood cultures and aspirate pus when feasible","Identify dental/ENT, haematogenous, traumatic or postoperative source","Drain large abscesses and resistant-organism infections"],options:["Haematogenous/contiguous community source: ceftriaxone plus metronidazole, with vancomycin when staphylococcal risk exists","Post-neurosurgical or healthcare-associated infection: choose MRSA and resistant Gram-negative coverage using local susceptibility","Treat at least 4-6 weeks and until radiological stabilisation; selected completely excised abscesses may require shorter specialist-directed treatment"],source:"ICMR 2019 Table 8.5; neurosurgery and ID input are required."},
  {name:"Cellulitis",cat:"Skin & soft tissue",pages:"55-57",tests:["Differentiate cellulitis from abscess, stasis dermatitis and necrotising infection","Obtain blood/pus cultures before antibiotics when clinically indicated","Consider polymicrobial infection in diabetes and MRSA/TSS risk"],options:["Preferred: cefazolin or oral cephalexin","Alternative: amoxicillin-clavulanate","Consider clindamycin only for appropriate toxin/MRSA considerations. Usual duration 5-7 days, longer only if clinically indicated"],source:"ICMR 2019 Table 6.1; narrow to culture and clinical response."},
  {name:"Cutaneous abscess",cat:"Skin & soft tissue",pages:"55-57",tests:["Incision and drainage is the principal treatment","Culture severe, recurrent, complicated or healthcare-associated abscesses","Assess systemic illness, immune compromise and deep extension"],options:["Uncomplicated abscess: drainage may be sufficient without antibiotics","When antibiotics are indicated, select anti-staphylococcal therapy from local susceptibility; ICMR lists clindamycin for selected community SSTI","Severe/MRSA infection: use culture-directed vancomycin or linezolid under specialist review; typical uncomplicated adjunct course 5-7 days"],source:"ICMR 2019 SSTI chapter; source control comes first."},
  {name:"Necrotising fasciitis",cat:"Emergency",pages:"55-57",tests:["Immediate surgical exploration and repeated debridement - do not wait for imaging","Send blood and intraoperative specimens","Assess water exposure, shock and streptococcal toxic shock"],options:["Polymicrobial/unknown source: piperacillin-tazobactam plus clindamycin","Fresh/salt-water exposure with Aeromonas or Vibrio risk: ciprofloxacin plus doxycycline","Treat approximately 14 days after adequate source control, individualised to surgery and clinical response; consider IVIG only for selected streptococcal NF/TSS with specialist input"],source:"ICMR 2019 Table 6.1; surgery is lifesaving and antibiotics are adjunctive."},
  {name:"Acute uncomplicated cystitis",cat:"Urinary",pages:"86-91",tests:["Confirm lower urinary symptoms and collect urine culture when indicated","Do not treat pyuria alone or asymptomatic bacteriuria except recognised indications","Check eGFR, pregnancy and upper-tract/systemic features"],options:["Nitrofurantoin 100 mg twice daily for 5 days","Alternative fosfomycin 3 g single dose or co-trimoxazole DS twice daily for 3 days when susceptible","Avoid nitrofurantoin/fosfomycin if pyelonephritis, prostatitis or systemic infection is suspected; review renal suitability"],source:"ICMR 2019 Tables 9.2-9.3; local urinary susceptibility takes priority."},
  {name:"Acute pyelonephritis / complicated UTI",cat:"Urinary",pages:"86-91",tests:["Collect urine culture before first antibiotic and blood cultures if febrile/systemically ill","Assess obstruction, abscess and need for urgent drainage","Review prior ESBL/MDR isolates and recent antibiotics"],options:["Preferred empiric choices in the guide: piperacillin-tazobactam or ertapenem","Alternatives: imipenem, meropenem or amikacin; select only according to severity, ESBL risk and local antibiogram","Minimum 7 days; complicated UTI commonly 7-14 days. Review IV therapy at 48 hours and step down to a susceptible oral drug"],source:"ICMR 2019 Table 9.2; carbapenems should be reserved for justified resistance risk."},
  {name:"Community-acquired intra-abdominal infection",cat:"Abdominal",pages:"45-50",tests:["Obtain early surgical/source-control assessment","Differentiate mild/moderate from severe and healthcare-associated infection","Avoid redundant double anaerobic coverage"],options:["Mild-moderate community infection: cefoperazone-sulbactam; alternative piperacillin-tazobactam","Severe community infection: imipenem or meropenem","After adequate source control, 3-5 days may suffice in selected stable patients; otherwise commonly 4-7 days. Narrow to cultures"],source:"ICMR 2019 Table 5.1; local ESBL prevalence and source control determine selection."},
  {name:"Biliary tract infection",cat:"Abdominal",pages:"45-50",tests:["Assess cholangitis severity and need for urgent biliary drainage","Obtain blood/bile cultures in severe disease or during drainage","Review healthcare exposure and ESBL risk"],options:["Treat as community-acquired complicated intra-abdominal infection: cefoperazone-sulbactam or piperacillin-tazobactam for mild-moderate disease","Severe infection or strong ESBL risk: imipenem or meropenem","Drain obstruction promptly and narrow after cultures; duration depends on source control and bacteraemia"],source:"ICMR 2019 Table 5.1; drainage is central to cure."},
  {name:"Spontaneous bacterial peritonitis",cat:"Abdominal",pages:"49-52",tests:["Perform diagnostic paracentesis before antibiotics; inoculate ascitic fluid directly into blood-culture bottles","Treat when PMN count is at least 250 cells/mm3 while excluding secondary peritonitis","Obtain simultaneous blood cultures and assess MDR exposure"],options:["ICMR empiric option where community ESBL prevalence exceeds 10%: piperacillin-tazobactam or cefoperazone-sulbactam","Possible MDR infection: imipenem or meropenem based on risk and local susceptibility","Reassess response and distinguish secondary peritonitis requiring surgery"],source:"ICMR 2019 SBP section; cirrhosis care and albumin decisions require current hepatology protocol."},
  {name:"Catheter-related bloodstream infection",cat:"Bloodstream / HAI",pages:"104-111",tests:["Obtain paired catheter and peripheral blood cultures before antibiotics","Search for another infection source and assess exit-site/tunnel infection","Decide promptly whether device removal is required"],options:["Empiric Gram-positive/MRSA coverage is usually vancomycin or teicoplanin when local risk warrants","Add Gram-negative coverage for shock, neutropenia or local resistant Gram-negative risk, selected by antibiogram","Tailor to organism and clearance; remove catheter for severe sepsis, persistent bacteraemia or organisms for which retention is unsafe"],source:"ICMR 2019 CLABSI chapter; duration is organism- and complication-specific."},
  {name:"Pelvic inflammatory disease",cat:"Gynaecologic",pages:"142-152",tests:["Test for gonorrhoea/chlamydia and pregnancy; assess tubo-ovarian abscess and sepsis","Obtain cultures/NAAT where available before therapy","Ensure partner management and STI follow-up"],options:["Use a current PID combination regimen covering gonococcus, chlamydia and anaerobes; route depends on severity","Hospitalise for pregnancy, severe illness, tubo-ovarian abscess, inability to tolerate oral therapy or uncertain diagnosis","For puerperal sepsis/septic abortion/chorioamnionitis, ICMR lists piperacillin-tazobactam; escalate to imipenem plus MRSA cover only for prior antibiotics, shock or intubation"],source:"ICMR 2019 pelvic infection chapter; use current national STI dosing and specialist care."},
  {name:"Infective endocarditis",cat:"Cardiac",pages:"154-163",tests:["Draw three blood-culture sets at approximately 30-minute intervals before antibiotics when stable","Perform TTE/TEE as indicated and assess urgent surgical criteria","Identify native versus prosthetic valve and staphylococcal risk"],options:["Stable native-valve IE without staphylococcal risk: ampicillin-sulbactam; alternative ampicillin plus ceftriaxone, with gentamicin only when the specialist regimen requires synergy","Native-valve IE with S. aureus risk: vancomycin pending culture; daptomycin alternative in selected cases. If MSSA is likely/confirmed, flucloxacillin or cefazolin","Prosthetic-valve IE pending cultures: ceftriaxone plus vancomycin plus gentamicin plus rifampicin in the ICMR 2019 table. Definitive therapy must be culture/MIC-directed with ID and cardiac-surgery review"],source:"ICMR 2019 Table 13.3; toxicity and interactions require specialist monitoring."},
  {name:"Sepsis - source unclear",cat:"Emergency",pages:"29-34",tests:["Measure lactate, obtain at least two blood-culture sets and seek the source immediately","Do not delay time-critical antimicrobials in septic shock","Review recent antibiotics, devices, immune status, tropical infections and local resistance"],options:["ICMR 2019 preferred: imipenem-cilastatin plus/minus amikacin; alternative meropenem or cefoperazone-sulbactam plus/minus amikacin","Add vancomycin/teicoplanin only for MRSA risk; polymyxin only for justified carbapenem-resistant Gram-negative risk; echinocandin only with invasive Candida risk","Combination therapy is advised initially in septic shock, followed by daily de-escalation. Most cases 7-10 days, longer only for defined complicated foci"],source:"ICMR 2019 Table 3.1; requires immediate resuscitation, source control and local ICU policy."}
];

const drugs = [
  {name:"Ceftaroline",page:"8",class:"Cephalosporin",spectrum:"MRSA, streptococci and many Gram-negative bacteria; not Pseudomonas, Acinetobacter or Gram-negative anaerobes.",use:"Historical restricted/salvage use for selected serious MRSA infections when Gram-negative coverage is also needed.",avoid:"Not routine first-line CAP or uncomplicated skin infection; not broad empiric Gram-negative therapy.",monitor:"Renal function; possible positive direct Coombs test.",note:"ID/stewardship review recommended."},
  {name:"Ceftolozane/tazobactam",page:"8–9",class:"Cephalosporin + beta-lactamase inhibitor",spectrum:"Strong Gram-negative and some MDR Pseudomonas activity; unreliable staphylococcal activity; not active against carbapenemase producers.",use:"Selected MDR Pseudomonas infection based on susceptibility and specialist review.",avoid:"Routine empiric cUTI/cIAI when standard narrower options are suitable.",monitor:"Renal function and dose adjustment.",note:"Resistance epidemiology and approved indications have evolved since 2015."},
  {name:"Colistin",page:"9",class:"Polymyxin",spectrum:"Some MDR Acinetobacter and Pseudomonas; no Gram-positive or anaerobic activity and intrinsic gaps including Proteus/Serratia/Providencia.",use:"Salvage option for susceptible MDR Gram-negative infection.",avoid:"Empiric monotherapy for suspected Gram-negative infection.",monitor:"Renal function, neurotoxicity and neuromuscular blockade.",note:"Formulation and unit conversions are safety-critical; pharmacist/ID oversight required."},
  {name:"Daptomycin",page:"10–11",class:"Lipopeptide",spectrum:"Gram-positive activity including many MRSA and VRE isolates; no Gram-negative activity.",use:"Selected bacteremia/endocarditis or VRE infections under specialist guidance.",avoid:"Never for pneumonia because pulmonary surfactant inactivates it.",monitor:"CK, muscle symptoms, renal function and eosinophilic pneumonia.",note:"Check organism MIC and source control for persistent bacteremia."},
  {name:"Ertapenem",page:"11",class:"Carbapenem",spectrum:"Many enteric Gram-negatives including ESBL producers and anaerobes; not Pseudomonas, Acinetobacter or Enterococcus.",use:"Selected intra-abdominal, diabetic foot, pelvic and ESBL urinary infections.",avoid:"Severe infection when Pseudomonas is suspected.",monitor:"Renal function, CNS adverse effects and gastrointestinal toxicity.",note:"Stewardship restriction is important to preserve carbapenem activity."},
  {name:"Fosfomycin",page:"11–12",class:"Phosphonic acid derivative",spectrum:"Urinary activity against multiple Gram-positive and Gram-negative organisms; susceptibility should be confirmed for MDR isolates.",use:"Oral option for selected uncomplicated lower UTI when alternatives are limited.",avoid:"Infections outside urinary tract, pyelonephritis/urosepsis and asymptomatic bacteriuria except defined indications.",monitor:"Renal function and clinical response.",note:"Local formulation/availability and susceptibility methods vary."},
  {name:"Linezolid",page:"12–13",class:"Oxazolidinone",spectrum:"Gram-positive activity including MRSA and VRE; no Gram-negative coverage.",use:"Selected resistant Gram-positive infections, including certain MRSA pneumonia/VRE cases.",avoid:"Routine prophylaxis or initial therapy when safer established options suffice.",monitor:"Weekly CBC, serotonergic interactions, neuropathy/optic neuritis with prolonged use and lactic acidosis.",note:"Excellent oral bioavailability supports IV-to-oral transition when appropriate."},
  {name:"Tigecycline",page:"13",class:"Glycylcycline",spectrum:"MRSA, VRE, anaerobes and many Gram-negatives; excludes Pseudomonas and Proteus.",use:"Selected complicated intra-abdominal/skin infection or salvage therapy when alternatives are unsuitable.",avoid:"Bacteremia due to low serum concentrations; not preferred for severe bloodstream infection.",monitor:"Nausea/vomiting and hepatic function.",note:"Review current safety warnings and indication-specific outcomes."},
  {name:"Trimethoprim/sulfamethoxazole",page:"14–15",class:"Folate antagonists",spectrum:"Broad activity including many community MRSA, Stenotrophomonas and susceptible urinary pathogens; unreliable for group A streptococcal monotherapy.",use:"Susceptibility-directed UTI, selected MRSA skin infection, Pneumocystis and Stenotrophomonas.",avoid:"Use caution with sulfonamide reaction, pregnancy context and interacting medicines.",monitor:"Creatinine, potassium, CBC, rash and relevant drug interactions.",note:"Dose and interval depend on indication and renal function."},
  {name:"Liposomal amphotericin B (AmBisome)",page:"16",class:"Polyene antifungal",spectrum:"Broad antifungal activity; organism-specific limitations apply.",use:"Severe invasive fungal infection when indicated by current specialist protocol.",avoid:"Do not substitute formulations mg-for-mg.",monitor:"Renal function, potassium, magnesium, infusion reactions and CBC.",note:"Specialist/pharmacy verification is essential."},
  {name:"Micafungin",page:"17",class:"Echinocandin",spectrum:"Candida activity; no Cryptococcus activity and limited urinary penetration.",use:"Invasive candidiasis and selected azole-refractory disease.",avoid:"Not preferred for candiduria or CNS/ocular disease because of penetration limitations.",monitor:"Liver tests and clinical response.",note:"Species and susceptibility guide step-down therapy."},
  {name:"Voriconazole",page:"19–20",class:"Triazole antifungal",spectrum:"Mould and yeast activity, including Aspergillus; gaps and resistance vary.",use:"Selected invasive mould/yeast infections under specialist guidance.",avoid:"Numerous major interactions; pregnancy and hepatic considerations require review.",monitor:"Drug level when indicated, liver tests, QT, visual/neurologic effects and skin toxicity.",note:"Interaction screening is mandatory."}
];

const safety = [
  ["1","Confirm infection","Is there a bacterial/fungal syndrome that benefits from antimicrobials? Obtain appropriate cultures before treatment when safe."],
  ["2","Define urgency","Recognise shock, meningitis, necrotising infection or another time-critical syndrome; escalate and treat without avoidable delay."],
  ["3","Check allergies","Document drug, reaction, timing and severity. Distinguish intolerance from immediate or severe delayed hypersensitivity."],
  ["4","Dose safely","Record weight, creatinine clearance, renal replacement therapy, hepatic function, age and pregnancy/lactation status."],
  ["5","Choose deliberately","Use likely source, prior cultures, recent antibiotics, healthcare exposure and the local antibiogram—then select the narrowest adequate option."],
  ["6","Plan source control","Drain, debride, remove infected devices or relieve obstruction promptly when indicated."],
  ["7","Set review point","Document indication, dose, route, start time, intended duration and a 48–72 hour antibiotic time-out."],
  ["8","Reassess results","At review: stop if infection is unlikely, narrow to cultures, switch IV to oral when eligible, and define stop date."],
  ["9","Monitor toxicity","Track organ function, blood counts, ECG/drug levels and interactions appropriate to the selected agent."]
];

const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const diseaseSelect=q('#diseaseSelect');
function fillDiseases(filter=''){
  const current=diseaseSelect.value; const items=diseases.filter(d=>(d.name+' '+d.cat).toLowerCase().includes(filter.toLowerCase()));
  diseaseSelect.innerHTML=items.map(d=>`<option value="${d.name}">${d.name} — ${d.cat}</option>`).join('');
  if(items.some(d=>d.name===current)) diseaseSelect.value=current;
  if(items.length) renderDisease(diseaseSelect.value);
}
function renderDisease(name){
  const d=diseases.find(x=>x.name===name)||diseases[0];
  const flags=[];
  if(q('#allergy').checked) flags.push('Severe beta-lactam allergy: verify reaction phenotype and use a current specialist pathway—cross-reactivity is side-chain dependent.');
  if(q('#renal').checked) flags.push('Renal impairment/dialysis: calculate renal function and adjust dose/interval; obtain pharmacy input for RRT.');
  if(q('#pregnancy').checked) flags.push('Pregnancy/breastfeeding: verify fetal/neonatal safety and gestation-specific guidance before selection.');
  if(q('#unstable').checked) flags.push('Unstable/sepsis: urgent senior/ID review, cultures and source control; do not delay time-critical therapy.');
  if(q('#immunocompromised').checked) flags.push('Immunocompromised/neutropenic: this general pathway is insufficient—use a dedicated febrile-neutropenia/transplant protocol.');
  q('#recommendation').innerHTML=`<div class="result-head"><div><h2>${d.name}</h2><div class="source">${d.cat} • Baseline guide pages ${d.pages}</div></div><span class="tag">Adult inpatient</span></div>
    ${flags.length?`<div class="alert red"><strong>Patient-specific escalation</strong><ul class="plain-list">${flags.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}
    <div class="alert amber"><strong>Guideline baseline:</strong> ${d.source}</div>
    <div class="section-title">VERIFY BEFORE TREATING</div><ul class="plain-list">${d.tests.map(x=>`<li>${x}</li>`).join('')}</ul>
    <div class="section-title">STEWARDSHIP PATHWAY</div>${d.options.map((x,i)=>`<div class="choice"><span class="choice-num">${i+1}</span><div><strong>${x}</strong><small>Confirm exact agent, dose, route and duration using current local guidance.</small></div></div>`).join('')}
    <div class="section-title">MANDATORY REVIEW</div><p>Document indication and review at 48–72 hours for stop, narrow, IV-to-oral switch, duration and adverse effects.</p>`;
}
function renderDrugList(filter=''){
  const items=drugs.filter(d=>Object.values(d).join(' ').toLowerCase().includes(filter.toLowerCase()));
  q('#drugList').innerHTML=items.map((d,i)=>`<button class="drug-item ${i===0?'active':''}" data-drug="${d.name}">${d.name}</button>`).join('');
  qa('.drug-item').forEach(b=>b.onclick=()=>{qa('.drug-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDrug(b.dataset.drug)});
  if(items.length) renderDrug(items[0].name); else q('#drugDetail').innerHTML='<p>No matching drug found.</p>';
}
function renderDrug(name){const d=drugs.find(x=>x.name===name);if(!d)return;q('#drugDetail').innerHTML=`<div class="result-head"><div><h2>${d.name}</h2><div class="source">${d.class} • Supporting monograph page ${d.page}</div></div><span class="tag">Monograph</span></div><div class="alert amber"><strong>Verify current data:</strong> indications, resistance patterns, warnings and dosing may have changed; cross-check ICMR 2019 and current institutional policy.</div><div class="facts"><div class="fact"><span>SPECTRUM</span><p>${d.spectrum}</p></div><div class="fact"><span>SELECTED USE</span><p>${d.use}</p></div><div class="fact"><span>IMPORTANT LIMITATION</span><p>${d.avoid}</p></div><div class="fact"><span>MONITORING</span><p>${d.monitor}</p></div></div><div class="section-title">STEWARDSHIP NOTE</div><p>${d.note}</p><div class="section-title">BEFORE PRESCRIBING</div><p>Confirm indication, microbiology/MIC, allergy history, interactions, weight, pregnancy status, renal/hepatic function, route, duration and local approval requirements.</p>`}

qa('.nav').forEach(btn=>btn.onclick=()=>{qa('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');qa('.view').forEach(x=>x.classList.remove('active-view'));q('#'+btn.dataset.view+'View').classList.add('active-view')});
q('#diseaseSearch').oninput=e=>fillDiseases(e.target.value); diseaseSelect.onchange=()=>renderDisease(diseaseSelect.value); q('#reviewBtn').onclick=()=>renderDisease(diseaseSelect.value); qa('.controls input[type=checkbox]').forEach(x=>x.onchange=()=>renderDisease(diseaseSelect.value));
q('#drugSearch').oninput=e=>renderDrugList(e.target.value);
q('#safetyGrid').innerHTML=safety.map(([n,t,p])=>`<article class="safety-card"><span>${n}</span><h3>${t}</h3><p>${p}</p><label><input type="checkbox"> Reviewed</label></article>`).join('');
fillDiseases();renderDrugList();
