const diseases = [
  {name:"Community-acquired pneumonia",cat:"Pulmonary",pages:"83–86",tests:["Confirm infiltrate and severity; obtain cultures before antibiotics when severe","Assess aspiration, influenza and MRSA/Pseudomonas risk","Review at 48–72 hours and narrow to results"],options:["Non-severe inpatient: beta-lactam plus macrolide (verify current local CAP guideline)","Alternative: respiratory fluoroquinolone when appropriate","Add MRSA or antipseudomonal coverage only with validated risk factors"],source:"Baseline regimen category only; local resistance and current CAP guidance take priority."},
  {name:"Healthcare-acquired pneumonia",cat:"Pulmonary",pages:"87",tests:["Confirm new infiltrate plus compatible clinical features","Obtain respiratory and blood cultures","Use unit-specific antibiogram and recent antibiotic exposure"],options:["Choose empiric Gram-negative coverage from the local hospital protocol","Add MRSA coverage only when risk or local prevalence supports it","De-escalate promptly when culture and clinical data return"],source:"Historical HCAP terminology is outdated; use current HAP guidance."},
  {name:"Ventilator-associated pneumonia",cat:"Pulmonary",pages:"88–90",tests:["Collect lower respiratory sample before therapy when feasible","Assess shock, prior IV antibiotics and MDR colonisation","Apply local ICU antibiogram"],options:["Empiric antipseudomonal beta-lactam selected by local susceptibility","Consider a second antipseudomonal class only for high resistance risk","Add MRSA coverage according to local risk; de-escalate rapidly"],source:"Requires current ICU protocol; historical guide is baseline context only."},
  {name:"COPD exacerbation",cat:"Pulmonary",pages:"82",tests:["Antibiotics mainly when sputum purulence accompanies increased dyspnoea/volume or ventilation is needed","Exclude pneumonia and heart failure","Check recent antibiotics and prior Pseudomonas"],options:["Select a narrow oral agent per current local guideline when bacterial features are present","Reserve antipseudomonal therapy for defined risk factors","Typical short course if improving, per current protocol"],source:"Avoid antibiotics when bacterial criteria are absent."},
  {name:"Acute bacterial rhinosinusitis",cat:"ENT",pages:"78–79",tests:["Use bacterial criteria: persistent, severe or double-worsening illness","Exclude orbital/intracranial complications","Check immediate beta-lactam allergy"],options:["Amoxicillin/clavulanate is a common first-line category; verify current local dose/duration","Use a guideline-supported allergy alternative based on reaction phenotype","Reassess non-response rather than automatically broadening"],source:"Most acute sinusitis is viral."},
  {name:"Bacterial meningitis",cat:"CNS",pages:"73–74, 77",tests:["Emergency: cultures and immediate empiric therapy must not await delayed imaging/LP","Age, immune status, neurosurgery and resistance change coverage","Dexamethasone timing and public-health actions may apply"],options:["Use current emergency meningitis pathway with age/risk-tailored beta-lactam coverage","Add resistant pneumococcal and Listeria coverage when indicated","Seek urgent ID/neurology input and tailor to CSF/microbiology"],source:"Time-critical; consult current protocol immediately."},
  {name:"Brain abscess",cat:"CNS",pages:"76",tests:["Urgent imaging and neurosurgical assessment","Identify dental/ENT, haematogenous or postoperative source","Obtain abscess culture where feasible"],options:["Empiric therapy must cover likely source flora and anaerobes","Post-neurosurgical disease requires nosocomial Gram-negative/MRSA consideration","Tailor prolonged therapy to drainage, organism and imaging response"],source:"Specialist-managed; source control is central."},
  {name:"Cellulitis",cat:"Skin & soft tissue",pages:"100",tests:["Distinguish non-purulent cellulitis from abscess","Mark margins and assess systemic toxicity","Look for bite, water exposure, diabetic foot or necrotising infection"],options:["Non-purulent: target streptococci with the narrowest suitable beta-lactam","Purulent/MRSA risk: add an agent active against MRSA when indicated","Escalate severe disease and obtain surgical review if deep infection suspected"],source:"Do not use broad Gram-negative coverage for routine uncomplicated cellulitis."},
  {name:"Cutaneous abscess",cat:"Skin & soft tissue",pages:"101",tests:["Incision and drainage is primary therapy","Culture recurrent, severe or complicated abscesses","Assess systemic signs and immune compromise"],options:["Drainage alone may suffice for a small uncomplicated abscess","Add MRSA-active therapy for systemic illness or high-risk features","Use culture to narrow treatment"],source:"Source control comes before broader antibiotics."},
  {name:"Diabetic foot infection",cat:"Skin & soft tissue",pages:"103–104",tests:["Grade severity; assess perfusion and need for urgent surgery","Probe for osteomyelitis and obtain deep tissue specimen","Do not treat an uninfected ulcer"],options:["Mild infection: narrow Gram-positive coverage","Moderate/severe: broaden according to prior cultures, exposure and local flora","Antipseudomonal coverage is not automatic; use specific risk factors"],source:"Multidisciplinary wound, vascular and glycaemic management is required."},
  {name:"Necrotising soft-tissue infection",cat:"Emergency",pages:"107",tests:["Immediate surgical exploration—do not wait for imaging if clinical suspicion is high","Send tissue for Gram stain/culture","Treat shock and organ failure concurrently"],options:["Start broad empiric therapy covering Gram-positive, Gram-negative and anaerobic organisms","Include MRSA-active therapy and a toxin-suppressing agent when indicated","Narrow only after operative and microbiology findings"],source:"Surgical emergency; antibiotics are adjunctive to debridement."},
  {name:"Uncomplicated cystitis",cat:"Urinary",pages:"110–114",tests:["Confirm urinary symptoms; avoid treating asymptomatic bacteriuria except defined exceptions","Review pregnancy, renal function and prior cultures","Check local E. coli susceptibility"],options:["Use a recommended narrow oral urinary agent guided by local resistance","Fosfomycin may be an option for susceptible uncomplicated lower UTI","Avoid agents with poor urinary activity and avoid unnecessary broad therapy"],source:"Do not extrapolate uncomplicated cystitis regimens to pyelonephritis."},
  {name:"Pyelonephritis / urosepsis",cat:"Urinary",pages:"110–114",tests:["Obtain urine culture and blood cultures when systemically ill","Assess obstruction—urgent drainage may be required","Review prior ESBL/MDR organisms and recent antibiotics"],options:["Choose parenteral or oral therapy by severity and local susceptibility","Reserve carbapenem therapy for strong ESBL risk or confirmed susceptibility needs","Narrow promptly and ensure adequate tissue/serum exposure"],source:"Fosfomycin is not appropriate for systemic infection based on this guide."},
  {name:"Biliary tract infection",cat:"Abdominal",pages:"39–40",tests:["Assess obstruction, cholangitis severity and need for urgent drainage","Obtain cultures in severe infection or during drainage","Consider healthcare exposure and prior resistant organisms"],options:["Community-acquired mild/moderate: guideline-supported enteric Gram-negative coverage","Add anaerobic coverage only when anatomy/procedure indicates","Broader therapy for severe or healthcare-associated disease, then narrow"],source:"Source control and biliary drainage are decisive."},
  {name:"Diverticulitis",cat:"Abdominal",pages:"40–41",tests:["Confirm uncomplicated versus abscess/perforation","Selected uncomplicated cases may not need antibiotics under current guidance","Arrange drainage/surgery for complicated disease"],options:["When antibiotics are indicated, cover enteric Gram-negatives and anaerobes","Choose oral versus IV route by severity and absorption","Avoid unnecessarily prolonged courses after adequate source control"],source:"Current practice has changed since 2015; verify modern guidance."},
  {name:"Secondary peritonitis / GI perforation",cat:"Abdominal",pages:"42–46",tests:["Urgent source control assessment","Obtain intra-abdominal cultures in high-risk/severe cases","Differentiate community from healthcare-associated infection"],options:["Use a regimen covering enteric Gram-negatives and anaerobes","Broaden for severe healthcare-associated infection using local antibiogram","Shorten and narrow after effective source control and clinical response"],source:"ID/surgical review recommended for shock, failure or resistant isolates."},
  {name:"C. difficile infection",cat:"Gastrointestinal",pages:"47–50",tests:["Test only clinically significant unexplained diarrhoea","Stop inciting antibiotics and unnecessary acid suppression when possible","Assess fulminant disease: hypotension, ileus or megacolon"],options:["Use current CDI guideline—preferred agents have changed since this baseline","Fulminant CDI requires urgent combination therapy and surgical review","Do not treat an asymptomatic positive test"],source:"Historical regimens are intentionally not shown; consult current CDI guidance."},
  {name:"Catheter-related bloodstream infection",cat:"Bloodstream",pages:"60–64",tests:["Obtain paired peripheral and catheter blood cultures before antibiotics","Assess tunnel infection, prosthetic material and metastatic foci","Determine whether catheter removal is required"],options:["Empiric Gram-positive coverage according to MRSA risk","Add Gram-negative coverage for severe illness or defined risk","Tailor to organism and remove infected device when guideline indicates"],source:"Duration depends on organism, clearance and complications."},
  {name:"Infective endocarditis",cat:"Cardiac",pages:"65–70",tests:["Obtain at least three properly collected blood-culture sets before antibiotics if stable","Perform echo pathway and assess embolic/surgical indications","Identify native versus prosthetic valve/device"],options:["Empiric therapy depends on acuity, valve type and healthcare exposure","Definitive therapy must be organism/MIC-directed","Early ID and cardiac surgery involvement is recommended"],source:"Do not select definitive therapy without microbiology."},
  {name:"Sepsis — no clear source",cat:"Emergency",pages:"99",tests:["Obtain cultures promptly without delaying time-critical therapy","Search for drainable/removable source","Use local syndrome- and unit-specific antibiogram"],options:["Start severity-appropriate empiric therapy covering the most likely source and resistance risks","Avoid reflexively adding every broad agent; individualise to exposure and colonisation","Reassess within hours and de-escalate when source/data emerge"],source:"Emergency management and organ support take priority."}
];

const drugs = [
  {name:"Ceftaroline",page:"8",class:"Cephalosporin",spectrum:"MRSA, streptococci and many Gram-negative bacteria; not Pseudomonas, Acinetobacter or Gram-negative anaerobes.",use:"Historical restricted/salvage use for selected serious MRSA infections when Gram-negative coverage is also needed.",avoid:"Not routine first-line CAP or uncomplicated skin infection; not broad empiric Gram-negative therapy.",monitor:"Renal function; possible positive direct Coombs test.",note:"ID/stewardship review recommended."},
  {name:"Ceftolozane/tazobactam",page:"8–9",class:"Cephalosporin + beta-lactamase inhibitor",spectrum:"Strong Gram-negative and some MDR Pseudomonas activity; unreliable staphylococcal activity; not active against carbapenemase producers.",use:"Selected MDR Pseudomonas infection based on susceptibility and specialist review.",avoid:"Routine empiric cUTI/cIAI when standard narrower options are suitable.",monitor:"Renal function and dose adjustment.",note:"Resistance epidemiology and approved indications have evolved since 2015."},
  {name:"Colistin",page:"9",class:"Polymyxin",spectrum:"Some MDR Acinetobacter and Pseudomonas; no Gram-positive or anaerobic activity and intrinsic gaps including Proteus/Serratia/Providencia.",use:"Salvage option for susceptible MDR Gram-negative infection.",avoid:"Empiric monotherapy for suspected Gram-negative infection.",monitor:"Renal function, neurotoxicity and neuromuscular blockade.",note:"Formulation and unit conversions are safety-critical; pharmacist/ID oversight required."},
  {name:"Daptomycin",page:"10–11",class:"Lipopeptide",spectrum:"Gram-positive activity including many MRSA and VRE isolates; no Gram-negative activity.",use:"Selected bacteremia/endocarditis or VRE infections under specialist guidance.",avoid:"Never for pneumonia because pulmonary surfactant inactivates it.",monitor:"CK, muscle symptoms, renal function and eosinophilic pneumonia.",note:"Check organism MIC and source control for persistent bacteremia."},
  {name:"Ertapenem",page:"11",class:"Carbapenem",spectrum:"Many enteric Gram-negatives including ESBL producers and anaerobes; not Pseudomonas, Acinetobacter or Enterococcus.",use:"Selected intra-abdominal, diabetic foot, pelvic and ESBL urinary infections.",avoid:"Severe infection when Pseudomonas is suspected.",monitor:"Renal function, CNS adverse effects and gastrointestinal toxicity.",note:"Stewardship restriction is important to preserve carbapenem activity."},
  {name:"Fosfomycin",page:"11–12",class:"Phosphonic acid derivative",spectrum:"Urinary activity against multiple Gram-positive and Gram-negative organisms; susceptibility should be confirmed for MDR isolates.",use:"Oral option for selected uncomplicated lower UTI when alternatives are limited.",avoid:"Infections outside urinary tract, pyelonephritis/urosepsis and asymptomatic bacteriuria except defined indications.",monitor:"Renal function and clinical response.",note:"Local formulation/availability and susceptibility methods vary."},
  {name:"Linezolid",page:"12–13",class:"Oxazolidinone",spectrum:"Gram-positive activity including MRSA and VRE; no Gram-negative coverage.",use:"Selected resistant Gram-positive infections, including certain MRSA pneumonia/VRE cases.",avoid:"Routine prophylaxis or initial therapy when safer established options suffice.",monitor:"Weekly CBC, serotonergic interactions, neuropathy/optic neuritis with prolonged use and lactic acidosis.",note:"Excellent oral bioavailability supports IV-to-oral transition when appropriate."},
  {name:"Tigecycline",page:"13",class:"Glycylcycline",spectrum:"MRSA, VRE, anaerobes and many Gram-negatives; excludes Pseudomonas and Proteus.",use:"Selected complicated intra-abdominal/skin infection or salvage therapy when alternatives are unsuitable.",avoid:"Bacteremia due to low serum concentrations; not preferred for severe bloodstream infection.",monitor:"Nausea/vomiting and hepatic function.",note:"Review current safety warnings and indication-specific outcomes."},
  {name:"Trimethoprim/sulfamethoxazole",page:"14–15",class:"Folate antagonists",spectrum:"Broad activity including many community MRSA, Stenotrophomonas and susceptible urinary pathogens; unreliable for group A streptococcal monotherapy.",use:"Susceptibility-directed UTI, selected MRSA skin infection, Pneumocystis and Stenotrophomonas.",avoid:"Use caution with sulfonamide reaction, pregnancy context and interacting medicines.",monitor:"Creatinine, potassium, CBC, rash and relevant drug interactions.",note:"Dose and interval depend on indication and renal function."},
  {name:"Liposomal amphotericin B (AmBisome)",page:"16",class:"Polyene antifungal",spectrum:"Broad antifungal activity; organism-specific limitations apply.",use:"Severe invasive fungal infection when indicated by current specialist protocol.",avoid:"Do not substitute formulations mg-for-mg.",monitor:"Renal function, potassium, magnesium, infusion reactions and CBC.",note:"Specialist/pharmacy verification is essential."},
  {name:"Micafungin",page:"17",class:"Echinocandin",spectrum:"Candida activity; no Cryptococcus activity and limited urinary penetration.",use:"Invasive candidiasis and selected azole-refractory disease.",avoid:"Not preferred for candiduria or CNS/ocular disease because of penetration limitations.",monitor:"Liver tests and clinical response.",note:"Species and susceptibility guide step-down therapy."},
  {name:"Voriconazole",page:"19–20",class:"Triazole antifungal",spectrum:"Mould and yeast activity, including Aspergillus; gaps and resistance vary.",use:"Selected invasive mould/yeast infections under specialist guidance.",avoid:"Numerous major interactions; pregnancy and hepatic considerations require review.",monitor:"Drug level when indicated, liver tests, QT, visual/neurologic effects and skin toxicity.",note:"Interaction screening is mandatory."}
];

const safety = [
  ["1","Confirm infection","Is there a bacterial/fungal syndrome that benefits from antimicrobials? Obtain appropriate cultures before treatment when safe."],
  ["2","Define urgency","Recognise shock, meningitis, necrotising infection or another time-critical syndrome; escalate and treat without avoidable delay."],
  ["3","Check allergies","Document drug, reaction, timing and severity. Distinguish intolerance from immediate or severe delayed hypersensitivity."],
  ["4","Dose safely","Record weight, creatinine clearance, renal replacement therapy, hepatic function, age and pregnancy/lactation status."],
  ["5","Choose deliberately","Use likely source, prior cultures, recent antibiotics, healthcare exposure and the local antibiogram—then select the narrowest adequate option."],
  ["6","Plan source control","Drain, debride, remove infected devices or relieve obstruction promptly when indicated."],
  ["7","Set review point","Document indication, dose, route, start time, intended duration and a 48–72 hour antibiotic time-out."],
  ["8","Reassess results","At review: stop if infection is unlikely, narrow to cultures, switch IV to oral when eligible, and define stop date."],
  ["9","Monitor toxicity","Track organ function, blood counts, ECG/drug levels and interactions appropriate to the selected agent."]
];

const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const diseaseSelect=q('#diseaseSelect');
function fillDiseases(filter=''){
  const current=diseaseSelect.value; const items=diseases.filter(d=>(d.name+' '+d.cat).toLowerCase().includes(filter.toLowerCase()));
  diseaseSelect.innerHTML=items.map(d=>`<option value="${d.name}">${d.name} — ${d.cat}</option>`).join('');
  if(items.some(d=>d.name===current)) diseaseSelect.value=current;
  if(items.length) renderDisease(diseaseSelect.value);
}
function renderDisease(name){
  const d=diseases.find(x=>x.name===name)||diseases[0];
  const flags=[];
  if(q('#allergy').checked) flags.push('Severe beta-lactam allergy: verify reaction phenotype and use a current specialist pathway—cross-reactivity is side-chain dependent.');
  if(q('#renal').checked) flags.push('Renal impairment/dialysis: calculate renal function and adjust dose/interval; obtain pharmacy input for RRT.');
  if(q('#pregnancy').checked) flags.push('Pregnancy/breastfeeding: verify fetal/neonatal safety and gestation-specific guidance before selection.');
  if(q('#unstable').checked) flags.push('Unstable/sepsis: urgent senior/ID review, cultures and source control; do not delay time-critical therapy.');
  if(q('#immunocompromised').checked) flags.push('Immunocompromised/neutropenic: this general pathway is insufficient—use a dedicated febrile-neutropenia/transplant protocol.');
  q('#recommendation').innerHTML=`<div class="result-head"><div><h2>${d.name}</h2><div class="source">${d.cat} • Baseline guide pages ${d.pages}</div></div><span class="tag">Adult inpatient</span></div>
    ${flags.length?`<div class="alert red"><strong>Patient-specific escalation</strong><ul class="plain-list">${flags.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}
    <div class="alert amber"><strong>Historical baseline:</strong> ${d.source}</div>
    <div class="section-title">VERIFY BEFORE TREATING</div><ul class="plain-list">${d.tests.map(x=>`<li>${x}</li>`).join('')}</ul>
    <div class="section-title">STEWARDSHIP PATHWAY</div>${d.options.map((x,i)=>`<div class="choice"><span class="choice-num">${i+1}</span><div><strong>${x}</strong><small>Confirm exact agent, dose, route and duration using current local guidance.</small></div></div>`).join('')}
    <div class="section-title">MANDATORY REVIEW</div><p>Document indication and review at 48–72 hours for stop, narrow, IV-to-oral switch, duration and adverse effects.</p>`;
}
function renderDrugList(filter=''){
  const items=drugs.filter(d=>Object.values(d).join(' ').toLowerCase().includes(filter.toLowerCase()));
  q('#drugList').innerHTML=items.map((d,i)=>`<button class="drug-item ${i===0?'active':''}" data-drug="${d.name}">${d.name}</button>`).join('');
  qa('.drug-item').forEach(b=>b.onclick=()=>{qa('.drug-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDrug(b.dataset.drug)});
  if(items.length) renderDrug(items[0].name); else q('#drugDetail').innerHTML='<p>No matching drug found.</p>';
}
function renderDrug(name){const d=drugs.find(x=>x.name===name);if(!d)return;q('#drugDetail').innerHTML=`<div class="result-head"><div><h2>${d.name}</h2><div class="source">${d.class} • Baseline guide page ${d.page}</div></div><span class="tag">Monograph</span></div><div class="alert amber"><strong>Verify current data:</strong> indications, resistance patterns, warnings and dosing may have changed since 2015.</div><div class="facts"><div class="fact"><span>SPECTRUM</span><p>${d.spectrum}</p></div><div class="fact"><span>SELECTED USE</span><p>${d.use}</p></div><div class="fact"><span>IMPORTANT LIMITATION</span><p>${d.avoid}</p></div><div class="fact"><span>MONITORING</span><p>${d.monitor}</p></div></div><div class="section-title">STEWARDSHIP NOTE</div><p>${d.note}</p><div class="section-title">BEFORE PRESCRIBING</div><p>Confirm indication, microbiology/MIC, allergy history, interactions, weight, pregnancy status, renal/hepatic function, route, duration and local approval requirements.</p>`}

qa('.nav').forEach(btn=>btn.onclick=()=>{qa('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');qa('.view').forEach(x=>x.classList.remove('active-view'));q('#'+btn.dataset.view+'View').classList.add('active-view')});
q('#diseaseSearch').oninput=e=>fillDiseases(e.target.value); diseaseSelect.onchange=()=>renderDisease(diseaseSelect.value); q('#reviewBtn').onclick=()=>renderDisease(diseaseSelect.value); qa('.controls input[type=checkbox]').forEach(x=>x.onchange=()=>renderDisease(diseaseSelect.value));
q('#drugSearch').oninput=e=>renderDrugList(e.target.value);
q('#safetyGrid').innerHTML=safety.map(([n,t,p])=>`<article class="safety-card"><span>${n}</span><h3>${t}</h3><p>${p}</p><label><input type="checkbox"> Reviewed</label></article>`).join('');
fillDiseases();renderDrugList();
